# Generated by Django 3.1.7 on 2021-03-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_mailcheck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mailcheck',
            field=models.BooleanField(default='', verbose_name='Соглашение про отправку почты'),
        ),
    ]
