# Generated by Django 3.1.7 on 2021-03-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210306_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='mailcheck',
        ),
        migrations.AlterField(
            model_name='profile',
            name='u_sex',
            field=models.CharField(choices=[('0', ''), ('1', 'Мужской'), ('2', 'Женский')], default='', max_length=2, verbose_name='Выберите пол'),
        ),
    ]
