# Generated by Django 3.1.7 on 2021-03-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20210306_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='u_sex',
            field=models.CharField(choices=[('0', ''), ('2', 'Женский'), ('1', 'Мужской')], max_length=1, null=True, verbose_name='Выберите пол'),
        ),
    ]
