# Generated by Django 3.1.7 on 2021-03-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20210306_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='u_sex',
            field=models.CharField(choices=[('0', None), ('1', 'Мужской'), ('2', 'Женский')], max_length=1, null=True, verbose_name='Выберите пол'),
        ),
    ]
