# Generated by Django 3.1.7 on 2021-03-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20210306_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='u_sex',
            field=models.CharField(choices=[('0', ''), ('1', 'Мужской'), ('2', 'Женский')], default=None, max_length=1, verbose_name='Выберите пол'),
        ),
    ]
