# Generated by Django 3.1.7 on 2021-03-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20210306_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='u_sex',
            field=models.ImageField(choices=[('0', ''), ('1', 'Мужской'), ('2', 'Женский')], default='', upload_to='', verbose_name='Выберите пол'),
        ),
    ]
